##Review Classification  Part -1

In [110]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [111]:
data_yelp = pd.read_csv('/content/yelp_labelled.txt', sep='\t', header=None)


In [112]:
data_yelp.head()

# review and sentiment
# 0-Negative, 1-Positive for positive review

0  1
0                           Wow... Loved this place.  1
1                                 Crust is not good.  0
2          Not tasty and the texture was just nasty.  0
3  Stopped by during the late May bank holiday of...  1
4  The selection on the menu was great and so wer...  1

In [113]:
## Assign column names
columan_name = ['Review', 'Sentiment']
data_yelp.columns = columan_name

In [114]:
data_yelp.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [115]:
data_yelp.shape
##1000 rows (reviews), 2 columns (Sentiments)

(1000, 2)

In [116]:
data_amazon = pd.read_csv('/content/amazon_cells_labelled.txt', sep='\t', header=None)
data_amazon.head()
#review and sentiment
# 0-Negative, 1-Positive for positive review

0  1
0  So there is no way for me to plug it in here i...  0
1                        Good case, Excellent value.  1
2                             Great for the jawbone.  1
3  Tied to charger for conversations lasting more...  0
4                                  The mic is great.  1

In [117]:
data_amazon.columns = columan_name

In [118]:
data_amazon.head()

Review  Sentiment
0  So there is no way for me to plug it in here i...          0
1                        Good case, Excellent value.          1
2                             Great for the jawbone.          1
3  Tied to charger for conversations lasting more...          0
4                                  The mic is great.          1

In [119]:
data_amazon.shape


(1000, 2)

In [120]:
data_imdb = pd.read_csv('/content/imdb_labelled.txt', sep='\t', header=None)
data_imdb.head()

#review and sentiment
# 0-Negative, 1-Positive for positive review

0  1
0  A very, very, very slow-moving, aimless movie ...  0
1  Not sure who was more lost - the flat characte...  0
2  Attempting artiness with black & white and cle...  0
3       Very little music or anything to speak of.    0
4  The best scene in the movie was when Gerardo i...  1

In [121]:
data_imdb.columns = columan_name

In [122]:
data_imdb.head()


Review  Sentiment
0  A very, very, very slow-moving, aimless movie ...          0
1  Not sure who was more lost - the flat characte...          0
2  Attempting artiness with black & white and cle...          0
3       Very little music or anything to speak of.            0
4  The best scene in the movie was when Gerardo i...          1

In [123]:
data_imdb.shape

(748, 2)

In [124]:
##Append all the data in single dataframe

In [125]:
data = data_yelp.append([data_amazon, data_imdb],ignore_index=True)

# data= data[:2000]

In [126]:
data.shape

(2748, 2)

In [127]:
data.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [128]:
# check distribution of sentiments

In [129]:
data['Sentiment'].value_counts()
# 1346 positive reviews
# 1362 Negative reviews


1    1386
0    1362
Name: Sentiment, dtype: int64

In [130]:
# check for null values
data.isnull().sum()

# no null values in the data

Review       0
Sentiment    0
dtype: int64

In [131]:
x = data['Review']
y = data['Sentiment']

##Data Cleaning

In [132]:
## here we will remove stopwords, punctuations
## as well as we will apply lematization

###Create a function toclean the data

In [133]:
import string 


In [134]:
punct = string.punctuation

In [135]:
punct

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [136]:
from spacy.lang.en.stop_words import STOP_WORDS

In [137]:
stopwords = list(STOP_WORDS) # list of stopwords

In [138]:
stopwords

['herself',
 'two',
 'after',
 'thru',
 'was',
 'we',
 'does',
 'four',
 'her',
 'must',
 'whither',
 'since',
 'where',
 'mine',
 'also',
 'more',
 'keep',
 'me',
 'until',
 'hereafter',
 'whatever',
 'eight',
 'most',
 'off',
 'about',
 '‘d',
 'across',
 'used',
 'whoever',
 'perhaps',
 'them',
 'therein',
 'latterly',
 'fifteen',
 'why',
 'doing',
 'be',
 'became',
 'between',
 'seeming',
 'below',
 'then',
 'least',
 'before',
 'together',
 'really',
 '‘ve',
 'now',
 'will',
 'front',
 'down',
 'my',
 "'ve",
 'often',
 'neither',
 'others',
 'throughout',
 'rather',
 'would',
 'else',
 'even',
 'every',
 'show',
 'they',
 'without',
 'become',
 'nor',
 "'ll",
 'has',
 'part',
 'there',
 'back',
 'from',
 'this',
 'various',
 'is',
 'twelve',
 'three',
 'him',
 'none',
 'put',
 'own',
 'another',
 'ourselves',
 'anyhow',
 'next',
 'might',
 'had',
 'do',
 'ours',
 'nothing',
 'myself',
 'ca',
 '’s',
 'hereupon',
 'nine',
 'ten',
 'in',
 'yourself',
 'therefore',
 'besides',
 'beside

In [139]:
#creating a function for data cleaning

In [140]:
import spacy 

nlp = spacy.load('en_core_web_sm')

def text_data_cleaning(sentence):
  doc = nlp(sentence)

  tokens = [] # list of tokens
  for token in doc:
    if token.lemma_ != "-PRON-":
      temp = token.lemma_.lower().strip()
    else:
      temp = token.lower_
    tokens.append(temp)
  
  cleaned_tokens = []
  for token in tokens:
    if token not in stopwords and token not in punct:
      cleaned_tokens.append(token)
  return cleaned_tokens     

In [141]:
## if root form of that word is not pronoun then it is goingto convert that into lower form
# and if that word is a poper noun, then we aer directly taking lower form, because there is no lemma

In [142]:
text_data_cleaning("Hello all, It's a beautiful day outside there!")
#stopwords and punctuations removed

['hello', 'beautiful', 'day', 'outside']

### Vektorization Feature Engineering(TF-IDF)


In [143]:
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline

In [144]:
tfidf = TfidfVectorizer(tokenizer=text_data_cleaning)
#tokenizer=text_data_cleaning, tokenization will bedone according to this function

In [145]:
classifier = LinearSVC()

##Train the model

### Splitting the dataset into the Train and Test set

In [146]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.2 , random_state= 0 )

In [147]:
x_train.shape, x_test.shape
# 2198 samples in training dataset and 550 in test dataset

((2198,), (550,))

In [148]:
x_train.head()

2572    An Italian reviewer called this "a small, grea...
526                          And it was way to expensive.
1509    As an earlier review noted, plug in this charg...
144     Nice blanket of moz over top but i feel like t...
2483    The film gives meaning to the phrase, "Never i...
Name: Review, dtype: object

###Fit thex_train any_train

In [149]:
clf = Pipeline([('tfidf',tfidf), ('clf', classifier)])
# it will first do vectorization and then it will do classification

In [150]:
clf.fit(x_train, y_train)


Pipeline(steps=[('tfidf',
                 TfidfVectorizer(tokenizer=<function text_data_cleaning at 0x7fb6f4956820>)),
                ('clf', LinearSVC())])

## 4) Predict the Test set results

In [151]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


In [152]:
y_pred = clf.predict(x_test)


In [153]:
# confusion_matrix
confusion_matrix(y_test, y_pred)

array([[200,  79],
       [ 51, 220]])

In [154]:
# classification_report
print(classification_report(y_test, y_pred))
# we are getting almost 77% accuracy

              precision    recall  f1-score   support

           0       0.80      0.72      0.75       279
           1       0.74      0.81      0.77       271

    accuracy                           0.76       550
   macro avg       0.77      0.76      0.76       550
weighted avg       0.77      0.76      0.76       550



In [155]:
accuracy_score(y_test, y_pred)
# 76% accuracy

0.7636363636363637

In [156]:
clf.predict(["Wow, I am learning Natural Language Processing in fun fashion!"])
# output is 1, that means review is positive

array([1])

In [157]:
clf.predict(["It's hard to learn new things!"])
# output is 0, that means review is Negative

array([0])